server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:file:~/messages;AUTO_SERVER=true"
    username: "sa"
    password:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000     # 30 seconds
app:
  camel:
    routes:
      message:
        cronTrigger: "0/15 * * * * ?"
        generatorServiceUrl: http://localhost:8082/api
        consumerServiceUrl: http://localhost:8081/api
        pollingPeriod: 2000
        ftp:
          username: pionieerlabs
          password: changeme
          host: localhost
          port: 10021